name: clima_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Updated SDK version to align with the latest stable Flutter SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  # Updated version for cupertino_icons to the latest stable version
  geolocator: ^13.0.1
  http: ^1.2.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/  # Ensure the indentation is correct

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
